# Aula 02 - Python

## Dados numéricos

In [6]:
# Variável inteira
a = 1
print('Valor de a= '+str(a))
type(a)

Valor de a= 1


int

In [7]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [8]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [9]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [12]:
# Operação com NaN. Obs.: A propriedade global NaN é um valor especial que significa Not-A-Number (não é um número).
# nansum — Soma de valores ignorando NAN's
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de Texto

In [14]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [16]:
# True siginifica que o resultado é verdadeiro
a == 1

True

In [19]:
h = (a==1)
print(h)
type(h)

True


bool

In [18]:
i = True
type(i)

bool

In [20]:
ii = 'True'
type(ii)

str

## Operação de comparação

In [21]:
# Operação ==
a==b

True

In [22]:
# Operação ><
a>b

False

In [23]:
# Operação !=
a!=b

False

In [24]:
# Operação >= ou <=
a>=b

True

## Operações Matemáticas

In [25]:
# Soma 
a+b

2.0

In [26]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [27]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [28]:
# Divisão
a/b

1.0

In [29]:
# Potencia
5**2

25

In [30]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [31]:
math.exp(0)

1.0

In [32]:
math.exp(a)

2.718281828459045

In [33]:
math.exp(-10)

4.5399929762484854e-05

In [34]:
import math as mt
mt.log(c)

0.0

In [35]:
mt.log10(100)

2.0

## Listas

In [36]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [37]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [38]:
myFirstList==a

False

In [39]:
myFirstList[0]==a

True

In [40]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [41]:
type(mySecList)

list

In [42]:
type(mySecList[2])

str

In [43]:
type(mySecList[1])

int

## Caminhos = path

In [44]:
path = r"C:\Users\Marilia\Documents\ENS5173_202401\ENS5173_202401"
print(path)

C:\Users\Marilia\Documents\ENS5173_202401\ENS5173_202401


In [45]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 'Aula01.ipynb',
 'inputs',
 'python',
 'README.md',
 'scripts',
 'venv']

In [46]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [47]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:\\Users\\Marilia\\Documents\\ENS5173_202401\\ENS5173_202401/.git'

In [48]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [49]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\Marilia\\Documents\\ENS5173_202401\\ENS5173_202401\\venv\\Scripts'

In [53]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\Marilia\\Documents\\')

In [54]:
os.getcwd()

'C:\\Users\\Marilia\\Documents'

In [55]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\Marilia\Documents/test


In [56]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\Marilia\Documents/test2


## Numpy array e Pandas DataFrames

In [57]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [58]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [59]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[1.82308094e-01 3.43074016e-01 6.57986214e-01 5.83264053e-01
  1.11592324e-01 5.29077030e-01 9.27711877e-01 7.70203027e-01
  6.86558836e-01 2.70772137e-02]
 [8.64812392e-01 9.47881642e-02 9.43735907e-01 5.48239386e-01
  9.87575062e-02 1.88991013e-02 3.38126076e-01 1.53042161e-01
  8.87409289e-01 9.35577078e-01]
 [2.51468308e-01 7.87956457e-01 8.03548014e-01 1.51635928e-01
  2.76587937e-01 8.42003511e-01 7.22578759e-01 6.23934878e-01
  2.52903162e-01 3.50866192e-01]
 [2.69327820e-01 3.81655293e-01 3.63803386e-01 2.87897626e-01
  7.94962854e-01 2.56313509e-01 4.38104224e-01 6.52192140e-01
  9.64575484e-02 7.46693827e-01]
 [4.61875930e-01 2.03441943e-01 2.09888938e-01 6.83124938e-01
  1.25671192e-01 3.90773676e-01 8.06574928e-01 5.38466926e-01
  1.90485975e-01 4.12987862e-01]
 [5.80669839e-01 9.06448980e-01 8.36851248e-01 6.94107722e-01
  5.37213205e-01 1.61515130e-01 5.14037034e-01 6.24098091e-01
  3.33570620e-01 4.30368553e-01]
 [9.43352917e-01 2.41324399e-01 7.31922880e-01 4.31971708e

In [60]:
# Acessando valores da matriz
n[0,:]

array([0.18230809, 0.34307402, 0.65798621, 0.58326405, 0.11159232,
       0.52907703, 0.92771188, 0.77020303, 0.68655884, 0.02707721])

In [61]:
n[:,0]

array([1.82308094e-01, 8.64812392e-01, 2.51468308e-01, 2.69327820e-01,
       4.61875930e-01, 5.80669839e-01, 9.43352917e-01, 4.41962565e-01,
       7.13671118e-05, 6.22101112e-01])

In [62]:
n[:,1:5]

array([[0.34307402, 0.65798621, 0.58326405, 0.11159232],
       [0.09478816, 0.94373591, 0.54823939, 0.09875751],
       [0.78795646, 0.80354801, 0.15163593, 0.27658794],
       [0.38165529, 0.36380339, 0.28789763, 0.79496285],
       [0.20344194, 0.20988894, 0.68312494, 0.12567119],
       [0.90644898, 0.83685125, 0.69410772, 0.5372132 ],
       [0.2413244 , 0.73192288, 0.43197171, 0.4422369 ],
       [0.22412178, 0.67202711, 0.59705565, 0.27267977],
       [0.24910449, 0.90770495, 0.17585577, 0.60887889],
       [0.84422792, 0.88422191, 0.01121362, 0.55867769]])

In [63]:
n[0,1:5]

array([0.34307402, 0.65798621, 0.58326405, 0.11159232])

In [64]:
n[0,-1]

0.02707721370399907

In [65]:
n[0,4:-1]

array([0.11159232, 0.52907703, 0.92771188, 0.77020303, 0.68655884])

In [66]:
n[0,4:]

array([0.11159232, 0.52907703, 0.92771188, 0.77020303, 0.68655884,
       0.02707721])

In [67]:
an = np.log(n*5)
print(an)

[[-0.09261929  0.53962885  1.19086661  1.07032264 -0.5834651   0.97281667
   1.53440384  1.34833679  1.23337456 -1.99962482]
 [ 1.46419523 -0.74667281  1.551529    1.00839466 -0.70564995 -2.359203
   0.52510146 -0.26760392  1.48998894  1.54284617]
 [ 0.2289996   1.37112546  1.39071957 -0.27683493  0.32421144  1.43746682
   1.28450906  1.13772863  0.23468929  0.56208757]
 [ 0.29761193  0.64620046  0.59829621  0.36428759  1.37997802  0.24808397
   0.78413947  1.18202184 -0.72921437  1.31733786]
 [ 0.83697894  0.01706331  0.04826116  1.2283604  -0.46464846  0.66981119
   1.39447943  0.99040871 -0.0487388   0.72510084]
 [ 1.06586497  1.51121738  1.43132897  1.2443098   0.98807768 -0.21371854
   0.94397795  1.13799019  0.51153723  0.76632457]
 [ 1.5511231   0.18782471  1.29735779  0.77004273  0.79352835  1.32085782
   0.95101319 -0.27352468  0.26489871  0.85428796]
 [ 0.79290782  0.11387221  1.21198132  1.09369295  0.30998074  0.72240801
   1.08923182  1.02227734 -0.91504265  1.51467128]
 [